apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000


---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users-api
          image: baitazar/kubernetes-azure-users:latest
          env:
            - name: MONGODB_CONNECTION_URI
              value: 'mongodb+srv://dawid:Lgy2YEtGah26Fwtg@kubernetes-azure.dxmakl3.mongodb.net/?retryWrites=true&w=majority&appName=kubernetes-azure'
            - name: AUTH_API_ADDRESSS
              value: 'auth-service.default:3000'
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            
